import express from 'express';
import { login, logout, SignUp } from '../controllers/AuthController.js';
const router=express.Router();
router.post('/signup', SignUp);
router.post('/login', login);
// router.post('/check-email',CheckMail);
router.post('/logout',logout);
// router.post('/reset-password',ResetPassword);
// router.post('/send-otp',SendOTP);
// router.post('/verify-otp',VerifyOTP);
export default router;